apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app 
  namespace: production
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: node-backend
          image: sidnal08/mern-backend:1.0
          ports:
            - containerPort: 3500
      initContainers:
        - name: init-dbservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup mysql-container.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
