apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: production
  labels:
    app: mysql-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: sidnal08/mern-mysql:1.0
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: MYSQL_ROOT_PASS

            - name: MYSQL_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: MYSQL_ROOT_USER
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pv-claim

      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
          volumeMounts:
            - name: db-data
              mountPath: var/lib/mysql 

    
